Diary/urls.py
from django.conf.urls import patterns, include, url

import Entry.views
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
admin.autodiscover()
from django.views.generic import TemplateView
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Diary.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$', 'Entry.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^$', Entry.views.home.as_view(), name='home'),
    url(r'^new/$', Entry.views.create.as_view(), name='new'),
    url(r'^update/(?P<pk>\d+)/$', Entry.views.update.as_view(), name='update'),
    url(r'^entry/(?P<pk>\d+)/$', Entry.views.EntryDetailView.as_view(), name='detail'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': 'home'}, name='logout'),
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^API/entrys/$','Entry.views.entry_list', name='listJSON'),
    url(r'^API/entrys/(?P<pk>[0-9]+)$', 'Entry.views.entry_view', name='viewJSON'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Entry/models.py
from _ast import mod
from django.db import models
import datetime
from ckeditor.widgets import CKEditorWidget
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.contrib import admin
# Create your models here.


class Entry(models.Model):
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    text = RichTextField(config_name='default')
    title = models.TextField()
    dateBegin = models.DateField()
    dateEnd = models.DateField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
            Override save so as to maintain modified and created date
        """
        if not self.id:
            self.created = datetime.datetime.today()
        self.modified = datetime.datetime.today()
        return super(Entry, self).save(*args, **kwargs)

    class Meta:
        permissions = (
            ('view_Entry', 'View Entry'),
            ('update_Entry', 'Update Entry'),
        )

Entry/forms.py
__author__ = 'jacob.cummings'
from django import forms
from Entry.models import Entry
from ckeditor.fields import RichTextFormField


class createEntry(forms.ModelForm):
    title = forms.CharField()
    text = RichTextFormField(config_name='default')
    dateBegin = forms.DateField()
    dateEnd = forms.DateField()
    def __init__(self, *args, **kwargs):
        super(createEntry, self).__init__(*args, **kwargs)
        self.fields["dateBegin"].label = "Start date of entry"
        self.fields["dateEnd"].label = "End date of entry"
    class Meta:
        model = Entry
        fields = ['title', 'text', 'dateBegin', 'dateEnd']

Entry/views.py
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponse
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, FormView, UpdateView, DetailView
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from Entry.models import Entry
from Entry.forms import createEntry
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from guardian.shortcuts import assign_perm
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from Entry.serializers import EntrySerializer, EntryViewSerializer
from rest_framework import mixins, generics, status
from rest_framework.response import Response
from Entry.permissions import CanView

class JSONResponse(HttpResponse):
        def __init__(self, data, **kwargs):
            content = JSONRenderer().render(data)
            kwargs['content_type'] = 'application/json'
            super(JSONResponse, self).__init__(content, **kwargs)


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)

@permission_classes((IsAuthenticated,CanView))
@api_view(['GET','POST'])
def entry_list(request):
    if request.method == 'GET':
        snippets = Entry.objects.filter(user = request.user)
        serializer = EntrySerializer(snippets, many=True)
        return Response(serializer.data)
    if request.method == 'POST':
        serializer = EntryViewSerializer

@permission_classes((IsAuthenticated,CanView))
@api_view(['GET','PUT'])
def entry_view(request, pk):
    try:
        entry = Entry.objects.get(pk=pk)
    except Entry.DoesNotExist:
        return  Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = EntryViewSerializer(entry)
        return Response(serializer.data)

    if request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = EntrySerializer(entry, data=data)
        if serializer.is_valid():
            serializer.save()
            return JSONResponse(serializer.data)
        return JSONResponse(serializer._errors, status=400)

class EntryList(generics.ListAPIView):
    serializer_class = EntrySerializer
    def get_queryset(self):
        return Entry.objects.filter(user = self.request.user)

class home(LoginRequiredMixin, ListView):
    template_name='entry_list.html'
    model = Entry
    paginate_by = 10
    def get_queryset(self):
       return Entry.objects.filter(user = self.request.user).order_by('-dateEnd', '-dateBegin')

class create(LoginRequiredMixin, FormView):
    form_class = createEntry
    template_name = 'entry_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        assign_perm('update_Entry', self.request.user, form.instance)
        assign_perm('view_Entry', self.request.user, form.instance)
        return super(create, self).form_valid(form)

    def get_success_url(self):
        return reverse("home")


class update(LoginRequiredMixin, UpdateView):
    form_class = createEntry
    template_name = 'entry_update.html'
    def form_valid(self, form):
        form.save()
        return super(update, self).form_valid(form)

    def get_success_url(self):
        return reverse('home')

    def get(self, request, **kwargs):
        self.object = Entry.objects.get(id=self.kwargs['pk'])
        if not self.request.user.has_perm('update_Entry', self.object):
            raise PermissionDenied()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)

    def get_object(self, queryset=None):
        obj = Entry.objects.get(id=self.kwargs['pk'])
        if not obj.user == self.request.user:
            raise Http404
        return obj


class EntryDetailView(LoginRequiredMixin, DetailView):
    model = Entry
    template_name = "entry_view.html"
    context_object_name = 'Entry'

    def get(self, request, *args, **kwargs):
        try:
            self.object = Entry.objects.get(id=self.kwargs['pk'])
        except Entry.DoesNotExist:
            raise Http404
        if not self.request.user.has_perm('view_Entry', self.object):
            raise PermissionDenied()
        return super(EntryDetailView, self).get(request, *args, **kwargs)


ckeditor_form_view = create.as_view()
ckeditor_update_view = update.as_view()

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <link rel="icon" type="image/ico" href="/static/favicon.png">
    {% load compress %}
    {% compress css %}
	    <link rel="stylesheet" href="/static/css/ui-darkness/jquery-ui-1.10.4.custom.min.css" />
	    <link rel="stylesheet" href="/static/css/style.css"/>
        <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css"/>
    {% endcompress %}
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
    {% compress js %}
        <script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
    {% endcompress %}
	{% block header %}
	{% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Diary</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'new' %}">New</a></li>
          </ul>
          {% if user.is_authenticated %}
            {{ user.first_name }}
          {% endif %}
          <form class="navbar-form navbar-right" role="search">
              <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
          </form>
            <ul class="nav navbar-right">
                <li><a class="btn btn-small" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
      </div>
    </nav>
    <div class="container">
        <div class="jumbotron">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</body>
<footer>
	{% block footer %}
	{% endblock %}
</footer>
{% compress js %}
    <script src="/static/js/jquery-2.1.0.min.js"></script>
    <script src="/static/js/jquery-ui-1.10.4.custom.min.js"></script>
    <script src="/static/js/jquery.shorten.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    {% block javascript %}
    {% endblock %}
{% endcompress %}
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
{% comment %}<script src="http://modernizr.com/downloads/modernizr-latest.js"></script>{% endcomment %}
<script>
</script>
</html>

templates/entry_create.html
{% extends 'base.html' %}
{% block header %}
    <title>New</title>
{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                <ul>
                    {% for error in field.errors %}
                        <li style="list-style-type: none">
                            <div class="alert alert-danger">
                                {{  error|escape }}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
        <input type="submit" value="Create">
    </form>
{% endblock %}
{% block javascript %}
    <script type="text/javascript">
        $("input#id_dateBegin").datepicker();
        $("input#id_dateEnd").datepicker();
    </script>
{% endblock %}

templates/entry_list.html
{% extends 'base.html' %}
{% block header %}
    <title>Diary</title>
{% endblock %}
{% block content %}
    <ul class="list-group">
        {% for entry in object_list %}
            <li class="list-group-item">
                <a href="{% url 'detail' pk=entry.id %}">{{ entry }}</a>
                <span id="entrys">{{ entry.text|safe }}</span>
                <a href="{% url 'update' pk=entry.id%}">Edit</a> <span>{{ entry.dateBegin }}</span> - <span class="float-right">{{ entry.dateEnd }}</span>
            </li>
        {% endfor %}
        {% if is_paginated %}
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% endif %}
                <li class="disabled"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
    </ul>
{% endblock %}
{% block footer %}
{% endblock %}
{% block javascript %}
<script type="text/javascript">
    $("span#entrys").each(function(index, element){
        $(element).shorten({
            showChars:'20'
        });
    });
</script>
{% endblock %}

templates/entry_update.html
{% extends 'base.html' %}
{% block header %}
    <title>Edit {{ form.title.value }}</title>
    <script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                <ul>
                    {% for error in field.errors %}
                        <li style="list-style-type: none">
                            <div class="alert alert-danger">
                                {{  error|escape }}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                {{ field.label_tag }}  {{ field }}
            </div>
        {% endfor %}
        <input type="submit" value="Save">
    </form>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $("input#id_dateBegin").datepicker();
        $("input#id_dateEnd").datepicker();
    </script>
{% endblock %}

templates/entry_view.html
{% extends 'base.html' %}
{% block header %}
    <title>{{ Entry }}</title>
{% endblock %}
{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">{{ Entry }}</div>
        <div class="panel-body">
            {{ Entry.text|safe }}
        </div>
    </div>
    <a href="{% url 'update' pk=Entry.id %}">Edit</a>
    <p>
        The date range for this entry is {{ Entry.dateBegin }} through {{ Entry.dateEnd }}
    </p>
    <h3>Date Created: {{ Entry.created }}</h3>
    <h4>Date Altered: {{ Entry.modified }}</h4>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
            <div class="input-group">
                <span class="input-group-addon">{{ form.username.label_tag }}</span>
                {{ form.username }}
            </div><br>
            <div class="input-group">
                <span class="input-group-addon">{{ form.password.label_tag }}</span>
                {{ form.password }}
            </div>
        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>

{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function() {
            $('input#id_password').addClass('form-control');
            $('input#id_username').addClass('form-control');
        });
    </script>
{% endblock %}